package com.jfshare.order.model;

import org.joda.time.DateTime;

public class TbOrderInfoRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.order_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.product_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.product_name
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.vice_name
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private String viceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.product_snapshoot_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private String productSnapshootId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.sku_num
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private String skuNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.sku_desc
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private String skuDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.seller_class_num
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private String sellerClassNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.cur_price
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private Integer curPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.org_price
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private Integer orgPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.images_url
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private String imagesUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.last_update_user_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private Integer lastUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.create_time
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private DateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.create_user_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.type
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.shelf
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private String shelf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.count
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.last_update_time
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private DateTime lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.subject_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.brand_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.wi
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private String wi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.exchange_score
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private Integer exchangeScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.exchange_cash
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private Integer exchangeCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.exchange_rule
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private String exchangeRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info_record.third_score
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    private Integer thirdScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.id
     *
     * @return the value of tb_order_info_record.id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.id
     *
     * @param id the value for tb_order_info_record.id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.order_id
     *
     * @return the value of tb_order_info_record.order_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.order_id
     *
     * @param orderId the value for tb_order_info_record.order_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.product_id
     *
     * @return the value of tb_order_info_record.product_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.product_id
     *
     * @param productId the value for tb_order_info_record.product_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.product_name
     *
     * @return the value of tb_order_info_record.product_name
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.product_name
     *
     * @param productName the value for tb_order_info_record.product_name
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.vice_name
     *
     * @return the value of tb_order_info_record.vice_name
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public String getViceName() {
        return viceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.vice_name
     *
     * @param viceName the value for tb_order_info_record.vice_name
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setViceName(String viceName) {
        this.viceName = viceName == null ? null : viceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.product_snapshoot_id
     *
     * @return the value of tb_order_info_record.product_snapshoot_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public String getProductSnapshootId() {
        return productSnapshootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.product_snapshoot_id
     *
     * @param productSnapshootId the value for tb_order_info_record.product_snapshoot_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setProductSnapshootId(String productSnapshootId) {
        this.productSnapshootId = productSnapshootId == null ? null : productSnapshootId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.sku_num
     *
     * @return the value of tb_order_info_record.sku_num
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public String getSkuNum() {
        return skuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.sku_num
     *
     * @param skuNum the value for tb_order_info_record.sku_num
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setSkuNum(String skuNum) {
        this.skuNum = skuNum == null ? null : skuNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.sku_desc
     *
     * @return the value of tb_order_info_record.sku_desc
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public String getSkuDesc() {
        return skuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.sku_desc
     *
     * @param skuDesc the value for tb_order_info_record.sku_desc
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setSkuDesc(String skuDesc) {
        this.skuDesc = skuDesc == null ? null : skuDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.seller_class_num
     *
     * @return the value of tb_order_info_record.seller_class_num
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public String getSellerClassNum() {
        return sellerClassNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.seller_class_num
     *
     * @param sellerClassNum the value for tb_order_info_record.seller_class_num
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setSellerClassNum(String sellerClassNum) {
        this.sellerClassNum = sellerClassNum == null ? null : sellerClassNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.cur_price
     *
     * @return the value of tb_order_info_record.cur_price
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public Integer getCurPrice() {
        return curPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.cur_price
     *
     * @param curPrice the value for tb_order_info_record.cur_price
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setCurPrice(Integer curPrice) {
        this.curPrice = curPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.org_price
     *
     * @return the value of tb_order_info_record.org_price
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public Integer getOrgPrice() {
        return orgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.org_price
     *
     * @param orgPrice the value for tb_order_info_record.org_price
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setOrgPrice(Integer orgPrice) {
        this.orgPrice = orgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.images_url
     *
     * @return the value of tb_order_info_record.images_url
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public String getImagesUrl() {
        return imagesUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.images_url
     *
     * @param imagesUrl the value for tb_order_info_record.images_url
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setImagesUrl(String imagesUrl) {
        this.imagesUrl = imagesUrl == null ? null : imagesUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.last_update_user_id
     *
     * @return the value of tb_order_info_record.last_update_user_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public Integer getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.last_update_user_id
     *
     * @param lastUpdateUserId the value for tb_order_info_record.last_update_user_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setLastUpdateUserId(Integer lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.create_time
     *
     * @return the value of tb_order_info_record.create_time
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public DateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.create_time
     *
     * @param createTime the value for tb_order_info_record.create_time
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setCreateTime(DateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.create_user_id
     *
     * @return the value of tb_order_info_record.create_user_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.create_user_id
     *
     * @param createUserId the value for tb_order_info_record.create_user_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.type
     *
     * @return the value of tb_order_info_record.type
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.type
     *
     * @param type the value for tb_order_info_record.type
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.shelf
     *
     * @return the value of tb_order_info_record.shelf
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public String getShelf() {
        return shelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.shelf
     *
     * @param shelf the value for tb_order_info_record.shelf
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setShelf(String shelf) {
        this.shelf = shelf == null ? null : shelf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.count
     *
     * @return the value of tb_order_info_record.count
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.count
     *
     * @param count the value for tb_order_info_record.count
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.last_update_time
     *
     * @return the value of tb_order_info_record.last_update_time
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public DateTime getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.last_update_time
     *
     * @param lastUpdateTime the value for tb_order_info_record.last_update_time
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setLastUpdateTime(DateTime lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.subject_id
     *
     * @return the value of tb_order_info_record.subject_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.subject_id
     *
     * @param subjectId the value for tb_order_info_record.subject_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.brand_id
     *
     * @return the value of tb_order_info_record.brand_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.brand_id
     *
     * @param brandId the value for tb_order_info_record.brand_id
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.wi
     *
     * @return the value of tb_order_info_record.wi
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public String getWi() {
        return wi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.wi
     *
     * @param wi the value for tb_order_info_record.wi
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setWi(String wi) {
        this.wi = wi == null ? null : wi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.exchange_score
     *
     * @return the value of tb_order_info_record.exchange_score
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public Integer getExchangeScore() {
        return exchangeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.exchange_score
     *
     * @param exchangeScore the value for tb_order_info_record.exchange_score
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setExchangeScore(Integer exchangeScore) {
        this.exchangeScore = exchangeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.exchange_cash
     *
     * @return the value of tb_order_info_record.exchange_cash
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public Integer getExchangeCash() {
        return exchangeCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.exchange_cash
     *
     * @param exchangeCash the value for tb_order_info_record.exchange_cash
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setExchangeCash(Integer exchangeCash) {
        this.exchangeCash = exchangeCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.exchange_rule
     *
     * @return the value of tb_order_info_record.exchange_rule
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public String getExchangeRule() {
        return exchangeRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.exchange_rule
     *
     * @param exchangeRule the value for tb_order_info_record.exchange_rule
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setExchangeRule(String exchangeRule) {
        this.exchangeRule = exchangeRule == null ? null : exchangeRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info_record.third_score
     *
     * @return the value of tb_order_info_record.third_score
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public Integer getThirdScore() {
        return thirdScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info_record.third_score
     *
     * @param thirdScore the value for tb_order_info_record.third_score
     *
     * @mbggenerated Wed Dec 16 16:44:14 CST 2015
     */
    public void setThirdScore(Integer thirdScore) {
        this.thirdScore = thirdScore;
    }
}