package com.jfshare.order.model.mappers;

import com.jfshare.order.model.TbOrderRecord;
import com.jfshare.order.model.TbOrderRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TbOrderRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_record
     *
     * @mbggenerated Sat May 28 14:58:42 CST 2016
     */
    int countByExample(TbOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_record
     *
     * @mbggenerated Sat May 28 14:58:42 CST 2016
     */
    int deleteByExample(TbOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_record
     *
     * @mbggenerated Sat May 28 14:58:42 CST 2016
     */
    @Delete({
        "delete from tb_order_record",
        "where order_id = #{orderId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_record
     *
     * @mbggenerated Sat May 28 14:58:42 CST 2016
     */
    @Insert({
        "insert into tb_order_record (order_id, trade_code, ",
        "user_id, user_name, ",
        "create_time, ",
        "cancel_time, ",
        "pay_time, ",
        "pay_account, seller_id, ",
        "seller_name, pay_channel, ",
        "pay_id, closing_price, ",
        "third_id, express_id, ",
        "express_no, province_id, ",
        "city_id, county_id, ",
        "receiver_address, receiver_name, ",
        "receiver_mobile, receiver_tele, ",
        "order_state, seller_comment, ",
        "buyer_comment, last_update_time, ",
        "last_update_user_id, create_user_id, ",
        "pay_state, address_id, ",
        "province_name, city_name, ",
        "county_name, post_code, ",
        "deliver_time, ",
        "success_time, ",
        "settlement_state, postage, ",
        "order_state_type, order_state_type_desc, ",
        "settlement_time, ",
        "order_tag, express_name, ",
        "wi, from_source, ",
        "trade_pay_id, order_delete_state, ",
        "exchange_score, exchange_cash, ",
        "order_batch, active_state, ",
        "third_score, postageExt, ",
        "order_type)",
        "values (#{orderId,jdbcType=VARCHAR}, #{tradeCode,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=INTEGER}, #{userName,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{cancelTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{payTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{payAccount,jdbcType=VARCHAR}, #{sellerId,jdbcType=INTEGER}, ",
        "#{sellerName,jdbcType=VARCHAR}, #{payChannel,jdbcType=INTEGER}, ",
        "#{payId,jdbcType=VARCHAR}, #{closingPrice,jdbcType=INTEGER}, ",
        "#{thirdId,jdbcType=VARCHAR}, #{expressId,jdbcType=INTEGER}, ",
        "#{expressNo,jdbcType=VARCHAR}, #{provinceId,jdbcType=INTEGER}, ",
        "#{cityId,jdbcType=INTEGER}, #{countyId,jdbcType=INTEGER}, ",
        "#{receiverAddress,jdbcType=VARCHAR}, #{receiverName,jdbcType=VARCHAR}, ",
        "#{receiverMobile,jdbcType=VARCHAR}, #{receiverTele,jdbcType=VARCHAR}, ",
        "#{orderState,jdbcType=INTEGER}, #{sellerComment,jdbcType=VARCHAR}, ",
        "#{buyerComment,jdbcType=VARCHAR}, #{lastUpdateTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{lastUpdateUserId,jdbcType=INTEGER}, #{createUserId,jdbcType=INTEGER}, ",
        "#{payState,jdbcType=INTEGER}, #{addressId,jdbcType=INTEGER}, ",
        "#{provinceName,jdbcType=VARCHAR}, #{cityName,jdbcType=VARCHAR}, ",
        "#{countyName,jdbcType=VARCHAR}, #{postCode,jdbcType=VARCHAR}, ",
        "#{deliverTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{successTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{settlementState,jdbcType=TINYINT}, #{postage,jdbcType=INTEGER}, ",
        "#{orderStateType,jdbcType=INTEGER}, #{orderStateTypeDesc,jdbcType=INTEGER}, ",
        "#{settlementTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{orderTag,jdbcType=INTEGER}, #{expressName,jdbcType=VARCHAR}, ",
        "#{wi,jdbcType=VARCHAR}, #{fromSource,jdbcType=INTEGER}, ",
        "#{tradePayId,jdbcType=VARCHAR}, #{orderDeleteState,jdbcType=INTEGER}, ",
        "#{exchangeScore,jdbcType=INTEGER}, #{exchangeCash,jdbcType=INTEGER}, ",
        "#{orderBatch,jdbcType=VARCHAR}, #{activeState,jdbcType=INTEGER}, ",
        "#{thirdScore,jdbcType=INTEGER}, #{postageext,jdbcType=VARCHAR}, ",
        "#{orderType,jdbcType=INTEGER})"
    })
    int insert(TbOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_record
     *
     * @mbggenerated Sat May 28 14:58:42 CST 2016
     */
    int insertSelective(TbOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_record
     *
     * @mbggenerated Sat May 28 14:58:42 CST 2016
     */
    List<TbOrderRecord> selectByExample(TbOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_record
     *
     * @mbggenerated Sat May 28 14:58:42 CST 2016
     */
    @Select({
        "select",
        "order_id, trade_code, user_id, user_name, create_time, cancel_time, pay_time, ",
        "pay_account, seller_id, seller_name, pay_channel, pay_id, closing_price, third_id, ",
        "express_id, express_no, province_id, city_id, county_id, receiver_address, receiver_name, ",
        "receiver_mobile, receiver_tele, order_state, seller_comment, buyer_comment, ",
        "last_update_time, last_update_user_id, create_user_id, pay_state, address_id, ",
        "province_name, city_name, county_name, post_code, deliver_time, success_time, ",
        "settlement_state, postage, order_state_type, order_state_type_desc, settlement_time, ",
        "order_tag, express_name, wi, from_source, trade_pay_id, order_delete_state, ",
        "exchange_score, exchange_cash, order_batch, active_state, third_score, postageExt, ",
        "order_type",
        "from tb_order_record",
        "where order_id = #{orderId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    TbOrderRecord selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_record
     *
     * @mbggenerated Sat May 28 14:58:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") TbOrderRecord record, @Param("example") TbOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_record
     *
     * @mbggenerated Sat May 28 14:58:42 CST 2016
     */
    int updateByExample(@Param("record") TbOrderRecord record, @Param("example") TbOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_record
     *
     * @mbggenerated Sat May 28 14:58:42 CST 2016
     */
    int updateByPrimaryKeySelective(TbOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_record
     *
     * @mbggenerated Sat May 28 14:58:42 CST 2016
     */
    @Update({
        "update tb_order_record",
        "set trade_code = #{tradeCode,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "user_name = #{userName,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "cancel_time = #{cancelTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "pay_time = #{payTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "pay_account = #{payAccount,jdbcType=VARCHAR},",
          "seller_id = #{sellerId,jdbcType=INTEGER},",
          "seller_name = #{sellerName,jdbcType=VARCHAR},",
          "pay_channel = #{payChannel,jdbcType=INTEGER},",
          "pay_id = #{payId,jdbcType=VARCHAR},",
          "closing_price = #{closingPrice,jdbcType=INTEGER},",
          "third_id = #{thirdId,jdbcType=VARCHAR},",
          "express_id = #{expressId,jdbcType=INTEGER},",
          "express_no = #{expressNo,jdbcType=VARCHAR},",
          "province_id = #{provinceId,jdbcType=INTEGER},",
          "city_id = #{cityId,jdbcType=INTEGER},",
          "county_id = #{countyId,jdbcType=INTEGER},",
          "receiver_address = #{receiverAddress,jdbcType=VARCHAR},",
          "receiver_name = #{receiverName,jdbcType=VARCHAR},",
          "receiver_mobile = #{receiverMobile,jdbcType=VARCHAR},",
          "receiver_tele = #{receiverTele,jdbcType=VARCHAR},",
          "order_state = #{orderState,jdbcType=INTEGER},",
          "seller_comment = #{sellerComment,jdbcType=VARCHAR},",
          "buyer_comment = #{buyerComment,jdbcType=VARCHAR},",
          "last_update_time = #{lastUpdateTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "last_update_user_id = #{lastUpdateUserId,jdbcType=INTEGER},",
          "create_user_id = #{createUserId,jdbcType=INTEGER},",
          "pay_state = #{payState,jdbcType=INTEGER},",
          "address_id = #{addressId,jdbcType=INTEGER},",
          "province_name = #{provinceName,jdbcType=VARCHAR},",
          "city_name = #{cityName,jdbcType=VARCHAR},",
          "county_name = #{countyName,jdbcType=VARCHAR},",
          "post_code = #{postCode,jdbcType=VARCHAR},",
          "deliver_time = #{deliverTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "success_time = #{successTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "settlement_state = #{settlementState,jdbcType=TINYINT},",
          "postage = #{postage,jdbcType=INTEGER},",
          "order_state_type = #{orderStateType,jdbcType=INTEGER},",
          "order_state_type_desc = #{orderStateTypeDesc,jdbcType=INTEGER},",
          "settlement_time = #{settlementTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "order_tag = #{orderTag,jdbcType=INTEGER},",
          "express_name = #{expressName,jdbcType=VARCHAR},",
          "wi = #{wi,jdbcType=VARCHAR},",
          "from_source = #{fromSource,jdbcType=INTEGER},",
          "trade_pay_id = #{tradePayId,jdbcType=VARCHAR},",
          "order_delete_state = #{orderDeleteState,jdbcType=INTEGER},",
          "exchange_score = #{exchangeScore,jdbcType=INTEGER},",
          "exchange_cash = #{exchangeCash,jdbcType=INTEGER},",
          "order_batch = #{orderBatch,jdbcType=VARCHAR},",
          "active_state = #{activeState,jdbcType=INTEGER},",
          "third_score = #{thirdScore,jdbcType=INTEGER},",
          "postageExt = #{postageext,jdbcType=VARCHAR},",
          "order_type = #{orderType,jdbcType=INTEGER}",
        "where order_id = #{orderId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TbOrderRecord record);
}