package com.jfshare.subject.bean.mapper;

import com.jfshare.subject.bean.TbSubjectBrandExample;
import com.jfshare.subject.bean.TbSubjectBrandKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface TbSubjectBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subject_brand
     *
     * @mbggenerated Thu Oct 08 18:36:18 CST 2015
     */
    int countByExample(TbSubjectBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subject_brand
     *
     * @mbggenerated Thu Oct 08 18:36:18 CST 2015
     */
    int deleteByExample(TbSubjectBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subject_brand
     *
     * @mbggenerated Thu Oct 08 18:36:18 CST 2015
     */
    @Delete({
        "delete from tb_subject_brand",
        "where brand_id = #{brandId,jdbcType=INTEGER}",
          "and subject_id = #{subjectId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(TbSubjectBrandKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subject_brand
     *
     * @mbggenerated Thu Oct 08 18:36:18 CST 2015
     */
    @Insert({
        "insert into tb_subject_brand (brand_id, subject_id)",
        "values (#{brandId,jdbcType=INTEGER}, #{subjectId,jdbcType=INTEGER})"
    })
    int insert(TbSubjectBrandKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subject_brand
     *
     * @mbggenerated Thu Oct 08 18:36:18 CST 2015
     */
    int insertSelective(TbSubjectBrandKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subject_brand
     *
     * @mbggenerated Thu Oct 08 18:36:18 CST 2015
     */
    List<TbSubjectBrandKey> selectByExample(TbSubjectBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subject_brand
     *
     * @mbggenerated Thu Oct 08 18:36:18 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbSubjectBrandKey record, @Param("example") TbSubjectBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subject_brand
     *
     * @mbggenerated Thu Oct 08 18:36:18 CST 2015
     */
    int updateByExample(@Param("record") TbSubjectBrandKey record, @Param("example") TbSubjectBrandExample example);
}