package com.jfshare.stock.model;

import org.joda.time.DateTime;

public class TbProductStock extends TbProductStockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_stock.active_count
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    private Integer activeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_stock.lock_count
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    private Integer lockCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_stock.create_time
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    private DateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_stock.last_update_time
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    private DateTime lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_stock.create_user_id
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_stock.last_update_user_id
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    private Integer lastUpdateUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_stock.active_count
     *
     * @return the value of tb_product_stock.active_count
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    public Integer getActiveCount() {
        return activeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_stock.active_count
     *
     * @param activeCount the value for tb_product_stock.active_count
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    public void setActiveCount(Integer activeCount) {
        this.activeCount = activeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_stock.lock_count
     *
     * @return the value of tb_product_stock.lock_count
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    public Integer getLockCount() {
        return lockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_stock.lock_count
     *
     * @param lockCount the value for tb_product_stock.lock_count
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    public void setLockCount(Integer lockCount) {
        this.lockCount = lockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_stock.create_time
     *
     * @return the value of tb_product_stock.create_time
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    public DateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_stock.create_time
     *
     * @param createTime the value for tb_product_stock.create_time
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    public void setCreateTime(DateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_stock.last_update_time
     *
     * @return the value of tb_product_stock.last_update_time
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    public DateTime getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_stock.last_update_time
     *
     * @param lastUpdateTime the value for tb_product_stock.last_update_time
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    public void setLastUpdateTime(DateTime lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_stock.create_user_id
     *
     * @return the value of tb_product_stock.create_user_id
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_stock.create_user_id
     *
     * @param createUserId the value for tb_product_stock.create_user_id
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_stock.last_update_user_id
     *
     * @return the value of tb_product_stock.last_update_user_id
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    public Integer getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_stock.last_update_user_id
     *
     * @param lastUpdateUserId the value for tb_product_stock.last_update_user_id
     *
     * @mbggenerated Mon Oct 19 21:52:45 CST 2015
     */
    public void setLastUpdateUserId(Integer lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId;
    }
}