package com.jfshare.express.model.mapper;

import com.jfshare.express.model.pojo.TbExpress;
import com.jfshare.express.model.pojo.TbExpressExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface TbExpressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_express
     *
     * @mbggenerated Tue Mar 24 16:07:26 CST 2015
     */
    int countByExample(TbExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_express
     *
     * @mbggenerated Tue Mar 24 16:07:26 CST 2015
     */
    int deleteByExample(TbExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_express
     *
     * @mbggenerated Tue Mar 24 16:07:26 CST 2015
     */
    @Delete({
        "delete from tb_express",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_express
     *
     * @mbggenerated Tue Mar 24 16:07:26 CST 2015
     */
    @Insert({
        "insert into tb_express (id, name, ",
        "query_url, status, ",
        "comment, last_update_time, ",
        "last_update_user_id, create_time, ",
        "create_user_id, kuaidi_key, ",
        "name_rule, express_no_rule, ",
        "grab_state, type_state, ",
        "dnf_tel, user_type, ",
        "serial_num)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{queryUrl,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, ",
        "#{comment,jdbcType=VARCHAR}, #{lastUpdateTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{lastUpdateUserId,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{createUserId,jdbcType=INTEGER}, #{kuaidiKey,jdbcType=VARCHAR}, ",
        "#{nameRule,jdbcType=VARCHAR}, #{expressNoRule,jdbcType=VARCHAR}, ",
        "#{grabState,jdbcType=INTEGER}, #{typeState,jdbcType=INTEGER}, ",
        "#{dnfTel,jdbcType=VARCHAR}, #{userType,jdbcType=INTEGER}, ",
        "#{serialNum,jdbcType=INTEGER})"
    })
    int insert(TbExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_express
     *
     * @mbggenerated Tue Mar 24 16:07:26 CST 2015
     */
    int insertSelective(TbExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_express
     *
     * @mbggenerated Tue Mar 24 16:07:26 CST 2015
     */
    List<TbExpress> selectByExample(TbExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_express
     *
     * @mbggenerated Tue Mar 24 16:07:26 CST 2015
     */
    @Select({
        "select",
        "id, name, query_url, status, comment, last_update_time, last_update_user_id, ",
        "create_time, create_user_id, kuaidi_key, name_rule, express_no_rule, grab_state, ",
        "type_state, dnf_tel, user_type, serial_num",
        "from tb_express",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TbExpress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_express
     *
     * @mbggenerated Tue Mar 24 16:07:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbExpress record, @Param("example") TbExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_express
     *
     * @mbggenerated Tue Mar 24 16:07:26 CST 2015
     */
    int updateByExample(@Param("record") TbExpress record, @Param("example") TbExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_express
     *
     * @mbggenerated Tue Mar 24 16:07:26 CST 2015
     */
    int updateByPrimaryKeySelective(TbExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_express
     *
     * @mbggenerated Tue Mar 24 16:07:26 CST 2015
     */
    @Update({
        "update tb_express",
        "set name = #{name,jdbcType=VARCHAR},",
          "query_url = #{queryUrl,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "comment = #{comment,jdbcType=VARCHAR},",
          "last_update_time = #{lastUpdateTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "last_update_user_id = #{lastUpdateUserId,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "create_user_id = #{createUserId,jdbcType=INTEGER},",
          "kuaidi_key = #{kuaidiKey,jdbcType=VARCHAR},",
          "name_rule = #{nameRule,jdbcType=VARCHAR},",
          "express_no_rule = #{expressNoRule,jdbcType=VARCHAR},",
          "grab_state = #{grabState,jdbcType=INTEGER},",
          "type_state = #{typeState,jdbcType=INTEGER},",
          "dnf_tel = #{dnfTel,jdbcType=VARCHAR},",
          "user_type = #{userType,jdbcType=INTEGER},",
          "serial_num = #{serialNum,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TbExpress record);
}