/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.jfshare.finagle.thrift.order;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OrderStateType implements TEnum {
  pay_timeout_cancel(101),
  buyer_cancel(102),
  refund_close(103),
  complain_close(104),
  scalper_close(105);

  private final int value;

  private OrderStateType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OrderStateType findByValue(int value) {
    switch (value) {
      case 101:
        return pay_timeout_cancel;
      case 102:
        return buyer_cancel;
      case 103:
        return refund_close;
      case 104:
        return complain_close;
      case 105:
        return scalper_close;
      default:
        return null;
    }
  }
}
