package com.jfshare.subject.bean;

import com.jfshare.subject.bean.support.Serialization;
import com.jfshare.subject.util.Commons;
import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

import java.util.HashMap;
import java.util.Map;

public class TbProductAttribute implements Serialization<Map<String, String>> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_attribute.id
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_attribute.name
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_attribute.subject_id
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_attribute.rewrite_id
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    private Integer rewriteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_attribute.type
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_attribute.value
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_attribute.required
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    private Integer required;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_attribute.is_sku
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    private Integer isSku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_attribute.demo
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    private String demo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_attribute.create_time
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    private DateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_attribute.creator
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_attribute.update_time
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    private DateTime updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_attribute.updater
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    private Integer updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_attribute.deleted
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    private Integer deleted;


    /**
     * 扩展字段1
     */
    private String ext1;

    /**
     * 扩展字段2
     */
    private String ext2;

    /**
     * 扩展字段3
     */
    private String ext3;

    /**
     * 扩展字段4
     */
    private String ext4;

    /**
     * 扩展字段5
     */
    private String ext5;

    /**
     * 扩展字段6
     */
    private String ext6;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_attribute.id
     *
     * @return the value of tb_product_attribute.id
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_attribute.id
     *
     * @param id the value for tb_product_attribute.id
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_attribute.name
     *
     * @return the value of tb_product_attribute.name
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_attribute.name
     *
     * @param name the value for tb_product_attribute.name
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_attribute.subject_id
     *
     * @return the value of tb_product_attribute.subject_id
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_attribute.subject_id
     *
     * @param subjectId the value for tb_product_attribute.subject_id
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_attribute.rewrite_id
     *
     * @return the value of tb_product_attribute.rewrite_id
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public Integer getRewriteId() {
        return rewriteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_attribute.rewrite_id
     *
     * @param rewriteId the value for tb_product_attribute.rewrite_id
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public void setRewriteId(Integer rewriteId) {
        this.rewriteId = rewriteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_attribute.type
     *
     * @return the value of tb_product_attribute.type
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_attribute.type
     *
     * @param type the value for tb_product_attribute.type
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_attribute.value
     *
     * @return the value of tb_product_attribute.value
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_attribute.value
     *
     * @param value the value for tb_product_attribute.value
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_attribute.required
     *
     * @return the value of tb_product_attribute.required
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public Integer getRequired() {
        return required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_attribute.required
     *
     * @param required the value for tb_product_attribute.required
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public void setRequired(Integer required) {
        this.required = required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_attribute.is_sku
     *
     * @return the value of tb_product_attribute.is_sku
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public Integer getIsSku() {
        return isSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_attribute.is_sku
     *
     * @param isSku the value for tb_product_attribute.is_sku
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public void setIsSku(Integer isSku) {
        this.isSku = isSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_attribute.demo
     *
     * @return the value of tb_product_attribute.demo
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public String getDemo() {
        return demo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_attribute.demo
     *
     * @param demo the value for tb_product_attribute.demo
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public void setDemo(String demo) {
        this.demo = demo == null ? null : demo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_attribute.create_time
     *
     * @return the value of tb_product_attribute.create_time
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public DateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_attribute.create_time
     *
     * @param createTime the value for tb_product_attribute.create_time
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public void setCreateTime(DateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_attribute.creator
     *
     * @return the value of tb_product_attribute.creator
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_attribute.creator
     *
     * @param creator the value for tb_product_attribute.creator
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_attribute.update_time
     *
     * @return the value of tb_product_attribute.update_time
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public DateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_attribute.update_time
     *
     * @param updateTime the value for tb_product_attribute.update_time
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public void setUpdateTime(DateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_attribute.updater
     *
     * @return the value of tb_product_attribute.updater
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public Integer getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_attribute.updater
     *
     * @param updater the value for tb_product_attribute.updater
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_attribute.deleted
     *
     * @return the value of tb_product_attribute.deleted
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_attribute.deleted
     *
     * @param deleted the value for tb_product_attribute.deleted
     *
     * @mbggenerated Mon Mar 23 11:36:53 CST 2015
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    public String getExt1() {
        return ext1;
    }

    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }

    public String getExt2() {
        return ext2;
    }

    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }

    public String getExt3() {
        return ext3;
    }

    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }

    public String getExt4() {
        return ext4;
    }

    public void setExt4(String ext4) {
        this.ext4 = ext4;
    }

    public String getExt5() {
        return ext5;
    }

    public void setExt5(String ext5) {
        this.ext5 = ext5;
    }

    public String getExt6() {
        return ext6;
    }

    public void setExt6(String ext6) {
        this.ext6 = ext6;
    }

    @Override
    public Map<String, String> serialize() {

        DateTimeFormatter formatter = DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss");
        Map<String, String> attributeMap = new HashMap<>();
        attributeMap.put("id", this.id.toString());
        attributeMap.put("name", this.name);
        attributeMap.put("subjectId", this.subjectId.toString());
        attributeMap.put("rewriteId", this.rewriteId == null ? "0" : this.rewriteId.toString());
        attributeMap.put("type", this.type);
        attributeMap.put("value", this.value);
        attributeMap.put("required", this.required.toString());
        attributeMap.put("isSku", this.isSku.toString());
        attributeMap.put("demo", this.demo == null ? "" : this.demo);
        attributeMap.put("createTime", this.createTime.toString(formatter));
        attributeMap.put("creator", this.creator.toString());
        attributeMap.put("updateTime", this.updateTime.toString(formatter));
        attributeMap.put("updater", this.updater.toString());
        attributeMap.put("deleted", this.deleted.toString());
        attributeMap.put("ext1", this.ext1);
        attributeMap.put("ext2", this.ext2);
        attributeMap.put("ext3", this.ext3);
        attributeMap.put("ext4", this.ext4);
        attributeMap.put("ext5", this.ext5);
        attributeMap.put("ext6", this.ext6);
        return attributeMap;
    }

    @Override
    public void deSerialize(Map<String, String> attributeMap) {
        DateTimeFormatter formatter = DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss");
        this.id = Integer.parseInt(attributeMap.get("id"));
        this.name = attributeMap.get("name");
        this.subjectId = Integer.parseInt(attributeMap.get("subjectId"));
        this.rewriteId = Integer.parseInt(attributeMap.get("rewriteId") == null ? "0" : attributeMap.get("rewriteId"));
        this.type = attributeMap.get("type");
        this.value = attributeMap.get("value");
        this.required = Integer.parseInt(attributeMap.get("required"));
        this.isSku = Integer.parseInt(attributeMap.get("isSku"));
        this.demo = attributeMap.get("demo");
        this.createTime = formatter.parseDateTime(attributeMap.get("createTime"));
        this.creator = Integer.parseInt(attributeMap.get("creator"));
        this.updateTime = formatter.parseDateTime(attributeMap.get("updateTime"));
        this.updater = Integer.parseInt(attributeMap.get("updater"));
        this.deleted = Integer.parseInt(attributeMap.get("deleted"));
        this.ext1 = attributeMap.get("ext1");
        this.ext2 = attributeMap.get("ext2");
        this.ext3 = attributeMap.get("ext3");
        this.ext4 = attributeMap.get("ext4");
        this.ext5 = attributeMap.get("ext5");
        this.ext6 = attributeMap.get("ext6");
    }

    @Override
    public int expireTime() {
        return 0;
    }

    @Override
    public String getCacheKey() {
        return Commons.PRODUCT_ATTRIBUTE_KEY + this.id;
    }
}