package com.jfshare.stock.model.mappers;

import com.jfshare.stock.model.TbProductStock;
import com.jfshare.stock.model.TbProductStockExample;
import com.jfshare.stock.model.TbProductStockKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TbProductStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_stock
     *
     * @mbggenerated Thu Apr 28 17:18:19 CST 2016
     */
    int countByExample(TbProductStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_stock
     *
     * @mbggenerated Thu Apr 28 17:18:19 CST 2016
     */
    int deleteByExample(TbProductStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_stock
     *
     * @mbggenerated Thu Apr 28 17:18:19 CST 2016
     */
    @Delete({
        "delete from tb_product_stock",
        "where product_id = #{productId,jdbcType=VARCHAR}",
          "and sku_num = #{skuNum,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TbProductStockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_stock
     *
     * @mbggenerated Thu Apr 28 17:18:19 CST 2016
     */
    @Insert({
        "insert into tb_product_stock (product_id, sku_num, ",
        "storehouse_id, active_count, ",
        "lock_count, create_time, ",
        "last_update_time, ",
        "create_user_id, last_update_user_id)",
        "values (#{productId,jdbcType=VARCHAR}, #{skuNum,jdbcType=VARCHAR}, ",
        "#{storehouseId,jdbcType=INTEGER}, #{activeCount,jdbcType=INTEGER}, ",
        "#{lockCount,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{lastUpdateTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{createUserId,jdbcType=INTEGER}, #{lastUpdateUserId,jdbcType=INTEGER})"
    })
    int insert(TbProductStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_stock
     *
     * @mbggenerated Thu Apr 28 17:18:19 CST 2016
     */
    int insertSelective(TbProductStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_stock
     *
     * @mbggenerated Thu Apr 28 17:18:19 CST 2016
     */
    List<TbProductStock> selectByExample(TbProductStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_stock
     *
     * @mbggenerated Thu Apr 28 17:18:19 CST 2016
     */
    @Select({
        "select",
        "product_id, sku_num, storehouse_id, active_count, lock_count, create_time, last_update_time, ",
        "create_user_id, last_update_user_id",
        "from tb_product_stock",
        "where product_id = #{productId,jdbcType=VARCHAR}",
          "and sku_num = #{skuNum,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    TbProductStock selectByPrimaryKey(TbProductStockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_stock
     *
     * @mbggenerated Thu Apr 28 17:18:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") TbProductStock record, @Param("example") TbProductStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_stock
     *
     * @mbggenerated Thu Apr 28 17:18:19 CST 2016
     */
    int updateByExample(@Param("record") TbProductStock record, @Param("example") TbProductStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_stock
     *
     * @mbggenerated Thu Apr 28 17:18:19 CST 2016
     */
    int updateByPrimaryKeySelective(TbProductStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_stock
     *
     * @mbggenerated Thu Apr 28 17:18:19 CST 2016
     */
    @Update({
        "update tb_product_stock",
        "set storehouse_id = #{storehouseId,jdbcType=INTEGER},",
          "active_count = #{activeCount,jdbcType=INTEGER},",
          "lock_count = #{lockCount,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "last_update_time = #{lastUpdateTime,jdbcType=TIMESTAMP,typeHandler=com.jfshare.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "create_user_id = #{createUserId,jdbcType=INTEGER},",
          "last_update_user_id = #{lastUpdateUserId,jdbcType=INTEGER}",
        "where product_id = #{productId,jdbcType=VARCHAR}",
          "and sku_num = #{skuNum,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TbProductStock record);
}