/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.jfshare.finagle.thrift.subject;

import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.Collections;

import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;

// No additional import required for struct/union.

public class SubjectTreeResult implements TBase<SubjectTreeResult, SubjectTreeResult._Fields>, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("SubjectTreeResult");

  private static final TField RESULT_FIELD_DESC = new TField("result", TType.STRUCT, (short)1);
  private static final TField SUBJECT_NODES_FIELD_DESC = new TField("subjectNodes", TType.LIST, (short)2);


  public com.jfshare.finagle.thrift.result.Result result;
  public List<SubjectNode> subjectNodes;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    RESULT((short)1, "result"),
    SUBJECT_NODES((short)2, "subjectNodes");
  
    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();
  
    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }
  
    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESULT
  	return RESULT;
        case 2: // SUBJECT_NODES
  	return SUBJECT_NODES;
        default:
  	return null;
      }
    }
  
    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }
  
    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }
  
    private final short _thriftId;
    private final String _fieldName;
  
    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }
  
    public short getThriftFieldId() {
      return _thriftId;
    }
  
    public String getFieldName() {
      return _fieldName;
    }
  }


  // isset id assignments

  public static final Map<_Fields, FieldMetaData> metaDataMap;
  static {
    Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESULT, new FieldMetaData("result", TFieldRequirementType.DEFAULT,
      new StructMetaData(TType.STRUCT, com.jfshare.finagle.thrift.result.Result.class)));
    tmpMap.put(_Fields.SUBJECT_NODES, new FieldMetaData("subjectNodes", TFieldRequirementType.DEFAULT,
      new ListMetaData(TType.LIST,
                new StructMetaData(TType.STRUCT, SubjectNode.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    FieldMetaData.addStructMetaDataMap(SubjectTreeResult.class, metaDataMap);
  }


  public SubjectTreeResult() {
  }

  public SubjectTreeResult(
    com.jfshare.finagle.thrift.result.Result result,
    List<SubjectNode> subjectNodes)
  {
    this();
    this.result = result;
    this.subjectNodes = subjectNodes;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SubjectTreeResult(SubjectTreeResult other) {
    if (other.isSetResult()) {
      this.result = new com.jfshare.finagle.thrift.result.Result(other.result);
    }
    if (other.isSetSubjectNodes()) {
      List<SubjectNode> __this__subjectNodes = new ArrayList<SubjectNode>();
      for (SubjectNode other_element : other.subjectNodes) {
        __this__subjectNodes.add(new SubjectNode(other_element));
      }
      this.subjectNodes = __this__subjectNodes;
    }
  }

  public SubjectTreeResult deepCopy() {
    return new SubjectTreeResult(this);
  }

  @Override
  public void clear() {
    this.result = null;
    this.subjectNodes = null;
  }

  public com.jfshare.finagle.thrift.result.Result getResult() {
    return this.result;
  }

  public SubjectTreeResult setResult(com.jfshare.finagle.thrift.result.Result result) {
    this.result = result;
    
    return this;
  }

  public void unsetResult() {
    this.result = null;
  }

  /** Returns true if field result is set (has been asigned a value) and false otherwise */
  public boolean isSetResult() {
    return this.result != null;
  }

  public void setResultIsSet(boolean value) {
    if (!value) {
      this.result = null;
    }
  }

  public int getSubjectNodesSize() {
    return (this.subjectNodes == null) ? 0 : this.subjectNodes.size();
  }

  public java.util.Iterator<SubjectNode> getSubjectNodesIterator() {
    return (this.subjectNodes == null) ? null : this.subjectNodes.iterator();
  }

  public void addToSubjectNodes(SubjectNode elem) {
    if (this.subjectNodes == null) {
      this.subjectNodes = new ArrayList<SubjectNode>();
    }
    this.subjectNodes.add(elem);
  }

  public List<SubjectNode> getSubjectNodes() {
    return this.subjectNodes;
  }

  public SubjectTreeResult setSubjectNodes(List<SubjectNode> subjectNodes) {
    this.subjectNodes = subjectNodes;
    
    return this;
  }

  public void unsetSubjectNodes() {
    this.subjectNodes = null;
  }

  /** Returns true if field subjectNodes is set (has been asigned a value) and false otherwise */
  public boolean isSetSubjectNodes() {
    return this.subjectNodes != null;
  }

  public void setSubjectNodesIsSet(boolean value) {
    if (!value) {
      this.subjectNodes = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RESULT:
      if (value == null) {
        unsetResult();
      } else {
        setResult((com.jfshare.finagle.thrift.result.Result)value);
      }
      break;
    case SUBJECT_NODES:
      if (value == null) {
        unsetSubjectNodes();
      } else {
        setSubjectNodes((List<SubjectNode>)value);
      }
      break;
    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RESULT:
      return getResult();
    case SUBJECT_NODES:
      return getSubjectNodes();
    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RESULT:
      return isSetResult();
    case SUBJECT_NODES:
      return isSetSubjectNodes();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SubjectTreeResult)
      return this.equals((SubjectTreeResult)that);
    return false;
  }

  public boolean equals(SubjectTreeResult that) {
    if (that == null)
      return false;
    boolean this_present_result = true && this.isSetResult();
    boolean that_present_result = true && that.isSetResult();
    if (this_present_result || that_present_result) {
      if (!(this_present_result && that_present_result))
        return false;
      if (!this.result.equals(that.result))
        return false;
    }
    boolean this_present_subjectNodes = true && this.isSetSubjectNodes();
    boolean that_present_subjectNodes = true && that.isSetSubjectNodes();
    if (this_present_subjectNodes || that_present_subjectNodes) {
      if (!(this_present_subjectNodes && that_present_subjectNodes))
        return false;
      if (!this.subjectNodes.equals(that.subjectNodes))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();
    boolean present_result = true && (isSetResult());
    builder.append(present_result);
    if (present_result)
      builder.append(result);
    boolean present_subjectNodes = true && (isSetSubjectNodes());
    builder.append(present_subjectNodes);
    if (present_subjectNodes)
      builder.append(subjectNodes);
    return builder.toHashCode();
  }

  public int compareTo(SubjectTreeResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    SubjectTreeResult typedOther = (SubjectTreeResult)other;

    lastComparison = Boolean.valueOf(isSetResult()).compareTo(typedOther.isSetResult());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResult()) {
      lastComparison = TBaseHelper.compareTo(this.result, typedOther.result);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSubjectNodes()).compareTo(typedOther.isSetSubjectNodes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSubjectNodes()) {
      lastComparison = TBaseHelper.compareTo(this.subjectNodes, typedOther.subjectNodes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) {
        break;
      }
      switch (field.id) {
        case 1: // RESULT
          if (field.type == TType.STRUCT) {
            this.result = new com.jfshare.finagle.thrift.result.Result();
            this.result.read(iprot);
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // SUBJECT_NODES
          if (field.type == TType.LIST) {
            {
            TList _list12 = iprot.readListBegin();
            this.subjectNodes = new ArrayList<SubjectNode>(_list12.size);
            for (int _i13 = 0; _i13 < _list12.size; ++_i13)
            {
              SubjectNode _elem14;
              _elem14 = new SubjectNode();
              _elem14.read(iprot);
              this.subjectNodes.add(_elem14);
            }
            iprot.readListEnd();
            }
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();
    
    oprot.writeStructBegin(STRUCT_DESC);
    if (this.result != null) {
      oprot.writeFieldBegin(RESULT_FIELD_DESC);
      this.result.write(oprot);
      oprot.writeFieldEnd();
    }
    if (this.subjectNodes != null) {
      oprot.writeFieldBegin(SUBJECT_NODES_FIELD_DESC);
      {
        oprot.writeListBegin(new TList(TType.STRUCT, this.subjectNodes.size()));
        for (SubjectNode _iter15 : this.subjectNodes)
        {
          _iter15.write(oprot);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SubjectTreeResult(");
    boolean first = true;
    sb.append("result:");
    if (this.result == null) {
      sb.append("null");
    } else {
      sb.append(this.result);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("subjectNodes:");
    if (this.subjectNodes == null) {
      sb.append("null");
    } else {
      sb.append(this.subjectNodes);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }
}
